import { AuthProvider } from "./context/authContext";
import "./globals.css";

export const metadata = {
  title: "Inkling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='montserrat'
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
